package asaan.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import asaan.dao.AddItem;
import asaan.dao.ModItem;

import asaan.dao.AddItemDao;
import asaan.dao.ModItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addItemDaoConfig;
    private final DaoConfig modItemDaoConfig;

    private final AddItemDao addItemDao;
    private final ModItemDao modItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addItemDaoConfig = daoConfigMap.get(AddItemDao.class).clone();
        addItemDaoConfig.initIdentityScope(type);

        modItemDaoConfig = daoConfigMap.get(ModItemDao.class).clone();
        modItemDaoConfig.initIdentityScope(type);

        addItemDao = new AddItemDao(addItemDaoConfig, this);
        modItemDao = new ModItemDao(modItemDaoConfig, this);

        registerDao(AddItem.class, addItemDao);
        registerDao(ModItem.class, modItemDao);
    }
    
    public void clear() {
        addItemDaoConfig.getIdentityScope().clear();
        modItemDaoConfig.getIdentityScope().clear();
    }

    public AddItemDao getAddItemDao() {
        return addItemDao;
    }

    public ModItemDao getModItemDao() {
        return modItemDao;
    }

}
