package asaan.dao;

import java.util.List;
import asaan.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ADD_ITEM.
 */
public class AddItem {

    private Long id;
    private int quantity;
    private int item_id;
    /** Not-null value. */
    private String order_for;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient AddItemDao myDao;

    private List<ModItem> modItemList;

    public AddItem() {
    }

    public AddItem(Long id) {
        this.id = id;
    }

    public AddItem(Long id, int quantity, int item_id, String order_for) {
        this.id = id;
        this.quantity = quantity;
        this.item_id = item_id;
        this.order_for = order_for;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getAddItemDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public int getItem_id() {
        return item_id;
    }

    public void setItem_id(int item_id) {
        this.item_id = item_id;
    }

    /** Not-null value. */
    public String getOrder_for() {
        return order_for;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrder_for(String order_for) {
        this.order_for = order_for;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ModItem> getModItemList() {
        if (modItemList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ModItemDao targetDao = daoSession.getModItemDao();
            List<ModItem> modItemListNew = targetDao._queryAddItem_ModItemList(id);
            synchronized (this) {
                if(modItemList == null) {
                    modItemList = modItemListNew;
                }
            }
        }
        return modItemList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetModItemList() {
        modItemList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
