package asaan.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import asaan.dao.AddItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ADD_ITEM.
*/
public class AddItemDao extends AbstractDao<AddItem, Long> {

    public static final String TABLENAME = "ADD_ITEM";

    /**
     * Properties of entity AddItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Quantity = new Property(1, int.class, "quantity", false, "QUANTITY");
        public final static Property Item_id = new Property(2, int.class, "item_id", false, "ITEM_ID");
        public final static Property Order_for = new Property(3, String.class, "order_for", false, "ORDER_FOR");
    };

    private DaoSession daoSession;


    public AddItemDao(DaoConfig config) {
        super(config);
    }
    
    public AddItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ADD_ITEM' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'QUANTITY' INTEGER NOT NULL ," + // 1: quantity
                "'ITEM_ID' INTEGER NOT NULL ," + // 2: item_id
                "'ORDER_FOR' TEXT NOT NULL );"); // 3: order_for
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ADD_ITEM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AddItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getQuantity());
        stmt.bindLong(3, entity.getItem_id());
        stmt.bindString(4, entity.getOrder_for());
    }

    @Override
    protected void attachEntity(AddItem entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AddItem readEntity(Cursor cursor, int offset) {
        AddItem entity = new AddItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // quantity
            cursor.getInt(offset + 2), // item_id
            cursor.getString(offset + 3) // order_for
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AddItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuantity(cursor.getInt(offset + 1));
        entity.setItem_id(cursor.getInt(offset + 2));
        entity.setOrder_for(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AddItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AddItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
