package asaan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MOD_ITEM.
 */
public class ModItem {

    private int quantity;
    private int item_id;

    public ModItem() {
    }

    public ModItem(int quantity, int item_id) {
        this.quantity = quantity;
        this.item_id = item_id;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public int getItem_id() {
        return item_id;
    }

    public void setItem_id(int item_id) {
        this.item_id = item_id;
    }

}
